# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package and Publish to GitHub Packages

run-name: 'Package Publish #${{github.run_number}}'

on:
  release:
    types: [published]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code       
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        server-id: 'github-package'
        cache: 'maven'

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{secrets.PACKAGE_PUBLISH_TOKEN}}

